### ISSUE TITLE
EV QEnvelopeView and curves

### ISSUE THREAD

**Issue by olafklingt** [nuss/Conductor#1]
I started to play around with your version of the Conductor quark. I realized that there is a problem with the EnvelopeViews under QT. 

because (QT)EnvelopeView does not implement curves it returns the envelopview itself.

Thats why the setting of curves has to be removed.

viewToEV { | view |
		var t, l, c, env;
		env = value;
		#t, l = view.value;
		env.levels = spec.map(l);
		env.times = t.differentiate[1..] * duration;
		//env.curves = view.curves;
		this.changed(\synch, this);
	}

because the envelop view doesn't provide a facility to change the curves it shouldn't matter.

and a the following is a test case. when you change the envelop in the gui you get an error.

(
c = Env.perc;
a = EV();
a.input = c;

a.value.times.debug(\t1);
a.value.levels.debug(\l1);
a.value.curves.debug(\c1);

b = EnvelopeView(w, Rect(0, 0, 230, 80))
.drawLines_(true)
.selectionColor_(Color.red)
.drawRects_(true)
.resize_(5)
.step_(0.05)
.action_({arg b; [b.index, b.value].postln})
.thumbSize_(5)
.value_([[0.0, 0.1, 0.5, 1.0],[0.1,1.0,0.8,0.0]]);
a.connect(b);
b.front;

a.value.times.debug(\t2);
a.value.levels.debug(\l2);
a.value.curves.debug(\c2);
)

**Comment by nuss** [comment]
@lonox - Thanks for the report! I must confess I haven't yet used EVs and I wasn't aware of the problem. The problem exists in the original version of Conductor as well (resp. it originates from there). I can reproduce it when I set `b.editable_(true)` and edit the envelop in the view with the mouse (if that's what you mean). 
I'm going to (preliminarily) comment out the line that causes the error now (I can confirm this prevents the error) but must admit I don't yet understand the internals of EV sufficiently. To me that line suggests that the envelope's curves are set from the view which isn't happening anymore? 
However, adding an action to the EV that posts the resulting Env as a compilestring and then setting the EV's value by providing a valid Env suggests that the EV is getting updated as well as the view is drawn correctly
```
// add the action EV sored in a
a.action_({ |ev| "Env(%, %, %)\n".postf(ev.value.levels, ev.value.times, ev.value.curves) });
// update the EV's value - view should be drawn accordingly
a.value_(Env([ 0, 0.7, 0 ], [ 0.35, 0.65 ], [0.5, -4]));
```
... if removing that one line from `viewToEV` is the proper fix then it should possibly go into the original Conductor too. I guess this should be discussed with Ron Kuivilla (I've already added a number of small fixes which I haven't discussed yet...)

**Comment by olafklingt** [comment]
You can look in the implementation of the EnvelopeView class that curves is not implemented in QT.  so the only case when the simple fix wouldn't be sufficient would be when someone sets the curves in the view directly (but why should someone do that).

**Comment by nuss** [comment]
Thanks @lonox! Hope, this is resolved now...
